name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Swift Version Info
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
